/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package task3;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.colorchooser.AbstractColorChooserPanel;

/**
 *
 * @author ebrarsahin
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    int red,green,blue;
  float cyan,black,magenta,yellow;
    public NewJFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_red = new javax.swing.JTextField();
        txt_green = new javax.swing.JTextField();
        txt_blue = new javax.swing.JTextField();
        txt_black = new javax.swing.JTextField();
        txt_yellow = new javax.swing.JTextField();
        txt_magenta = new javax.swing.JTextField();
        txt_cyan = new javax.swing.JTextField();
        toggle_rgbToCMYK = new javax.swing.JToggleButton();
        toggle_fromCMYK = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        txt_blue1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_red1 = new javax.swing.JTextField();
        txt_green1 = new javax.swing.JTextField();
        txt_b = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_h = new javax.swing.JTextField();
        txt_s = new javax.swing.JTextField();
        btn_rgbTOhsb = new javax.swing.JToggleButton();
        btn_hsbTOrgb = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        txt_red2 = new javax.swing.JTextField();
        txt_green2 = new javax.swing.JTextField();
        txt_l = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_h1 = new javax.swing.JTextField();
        txt_s1 = new javax.swing.JTextField();
        btn_rgbTOhsl = new javax.swing.JToggleButton();
        btn_hslTOrgb = new javax.swing.JToggleButton();
        txt_blue2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("RGB");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CMYK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("RED");

        jLabel2.setText("GREEN");

        jLabel3.setText("BLUE");

        jLabel4.setText("BLACK");

        jLabel5.setText("MAGENTA");

        jLabel6.setText("YELLOW");

        jLabel7.setText("CYAN");

        toggle_rgbToCMYK.setText(">");

        toggle_fromCMYK.setText("<");

        jLabel8.setText("RED");

        jLabel9.setText("GREEN");

        jLabel10.setText("BLUE");

        jLabel11.setText("HUE");

        jLabel12.setText("SATURATION");

        jLabel13.setText("BRIGHTNESS");

        btn_rgbTOhsb.setText("TO>>");
        btn_rgbTOhsb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rgbTOhsbActionPerformed(evt);
            }
        });

        btn_hsbTOrgb.setText("<<FROM");
        btn_hsbTOrgb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hsbTOrgbActionPerformed(evt);
            }
        });

        jLabel14.setText("BLUE");

        jLabel15.setText("HUE");

        jLabel16.setText("SATURATION");

        jLabel17.setText("LIGHTNESS");

        btn_rgbTOhsl.setText("TO>>");
        btn_rgbTOhsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rgbTOhslActionPerformed(evt);
            }
        });

        btn_hslTOrgb.setText("<<FROM");
        btn_hslTOrgb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hslTOrgbActionPerformed(evt);
            }
        });

        jLabel18.setText("RED");

        jLabel19.setText("GREEN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel14)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_blue2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_green2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_hslTOrgb, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txt_red2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_rgbTOhsl, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_s1)
                            .addComponent(txt_h1)
                            .addComponent(txt_l, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_red, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(txt_green)
                                    .addComponent(txt_blue))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(toggle_rgbToCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(toggle_fromCMYK, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_cyan, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(txt_magenta)
                                    .addComponent(txt_yellow)
                                    .addComponent(txt_black)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_red1)
                                    .addComponent(txt_green1)
                                    .addComponent(txt_blue1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_hsbTOrgb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_rgbTOhsb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_s)
                                    .addComponent(txt_b, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_h, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_b, txt_h, txt_s});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_red, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txt_cyan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toggle_rgbToCMYK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(txt_magenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txt_yellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(toggle_fromCMYK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_black, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_red1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_rgbTOhsb))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_green1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txt_blue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btn_hsbTOrgb))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt_h1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_rgbTOhsl)
                            .addComponent(txt_red2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_green2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txt_l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_blue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btn_hslTOrgb)))
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_b, txt_h, txt_s});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                JColorChooser cc = new JColorChooser();
                AbstractColorChooserPanel[] panels = cc.getChooserPanels();
                for (AbstractColorChooserPanel accp : panels) {
                    if (accp.getDisplayName().equals("RGB")) {
                        int reply=JOptionPane.showConfirmDialog(null, accp,"Choose RGB Color", JOptionPane.OK_CANCEL_OPTION);
                        if(reply== JOptionPane.OK_OPTION){
                            toggle_fromCMYK.setSelected(false);
                            red = cc.getColor().getRed(); txt_red.setText(red+"");
                            green = cc.getColor().getGreen(); txt_green.setText(green+"");
                            blue = cc.getColor().getBlue(); txt_blue.setText(blue+"");

                            black = Math.min(1 - red, 1 - green);
                            black = Math.min(black, 1 - blue);
                            cyan = (1 - red - black) / (1 - black);
                            magenta = (1 - green - black) / (1 - black);
                            yellow = (1 - blue - black) / (1 - black);
                            
                            txt_cyan.setText(cyan+"");
                            txt_magenta.setText(magenta+"");
                            txt_yellow.setText(yellow+"");
                            txt_black.setText(black+"");
                            
                            toggle_rgbToCMYK.setSelected(true);
                            
                            jTextField1.setBackground(cc.getColor());
                        }
                    }
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        JColorChooser cc = new JColorChooser();
        AbstractColorChooserPanel[] panels = cc.getChooserPanels();
        for (AbstractColorChooserPanel accp : panels) {
            if (accp.getDisplayName().equals("CMYK")) {
                int reply = JOptionPane.showConfirmDialog(null, accp, "Choose CMYK Color", JOptionPane.OK_CANCEL_OPTION);
                if (reply == JOptionPane.OK_OPTION) {
                    toggle_rgbToCMYK.setSelected(false);
                    
                    red = cc.getColor().getRed(); 
                    green = cc.getColor().getGreen(); 
                    blue = cc.getColor().getBlue(); 
                    
                    black = Math.min(1 - red, 1 - green);
                    black = Math.min(black, 1 - blue);
                    cyan = (1 - red - black) / (1 - black);
                    magenta = (1 - green - black) / (1 - black);
                    yellow = (1 - blue - black) / (1 - black);

                    red = (int) (1 - Math.min(1, cyan * (1 - black) + black));
                    green = (int) (1 - Math.min(1, magenta * (1 - black) + black));
                    blue = (int) (1 - Math.min(1, yellow * (1 - black) + black));
                    
                    txt_red.setText(red+"");
                    txt_green.setText(green+"");
                    txt_blue.setText(blue+"");
                    txt_cyan.setText(cyan + "");
                    txt_magenta.setText(magenta + "");
                    txt_yellow.setText(yellow + "");
                    txt_black.setText(black + "");
                    
                    toggle_fromCMYK.setSelected(true);
                    
                    jTextField1.setBackground(cc.getColor());
                }
            }
        }
            
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_rgbTOhsbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rgbTOhsbActionPerformed
        // TODO add your handling code here:
        JColorChooser cc = new JColorChooser();
                AbstractColorChooserPanel[] panels = cc.getChooserPanels();
                for (AbstractColorChooserPanel accp : panels) {
                    if (accp.getDisplayName().equals("RGB")) {
                        int reply=JOptionPane.showConfirmDialog(null, accp,"Choose RGB Color", JOptionPane.OK_CANCEL_OPTION);
                        if(reply== JOptionPane.OK_OPTION){
                            
                            red = cc.getColor().getRed(); txt_red1.setText(red+"");
                            green = cc.getColor().getGreen(); txt_green1.setText(green+"");
                            blue = cc.getColor().getBlue(); txt_blue1.setText(blue+"");

                            float [] hsb=Color.RGBtoHSB(red, green, blue, null);
                            
                            txt_h.setText(hsb[0]+"");
                            txt_s.setText(hsb[1]+"");
                            txt_b.setText(hsb[2]+"");
                            
                            jTextField1.setBackground(cc.getColor());
                        }
                    }
                }
    }//GEN-LAST:event_btn_rgbTOhsbActionPerformed

    private void btn_hsbTOrgbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hsbTOrgbActionPerformed
        // TODO add your handling code here:
        JColorChooser cc = new JColorChooser();
                AbstractColorChooserPanel[] panels = cc.getChooserPanels();
                for (AbstractColorChooserPanel accp : panels) {
                    if (accp.getDisplayName().equals("HSV")) {
                        int reply=JOptionPane.showConfirmDialog(null, accp,"Choose HSB Color", JOptionPane.OK_CANCEL_OPTION);
                        if(reply== JOptionPane.OK_OPTION){
                           
                            float [] hsb=cc.getColor().getComponents(null);
                            int rgb2=Color.HSBtoRGB(hsb[0], hsb[1], hsb[2]);
                            
                            txt_h.setText(hsb[0]+"");
                            txt_s.setText(hsb[1]+"");
                            txt_b.setText(hsb[2]+"");
                            
//                            float rgb[]=cc.getColor().getRGBComponents(null);
//                            txt_red1.setText(rgb[0]+"");
//                            txt_green1.setText(rgb[1]+"");
//                            txt_blue1.setText(rgb[2]+"");
                            red = cc.getColor().getRed(); txt_red1.setText(red+"");
                            green = cc.getColor().getGreen(); txt_green1.setText(green+"");
                            blue = cc.getColor().getBlue(); txt_blue1.setText(blue+"");
                            jTextField1.setBackground(cc.getColor());
                        }
                    }
                }
    }//GEN-LAST:event_btn_hsbTOrgbActionPerformed

    private void btn_rgbTOhslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rgbTOhslActionPerformed
        // TODO add your handling code here:
        JColorChooser cc = new JColorChooser();
                AbstractColorChooserPanel[] panels = cc.getChooserPanels();
                for (AbstractColorChooserPanel accp : panels) {
                    if (accp.getDisplayName().equals("RGB")) {
                        int reply=JOptionPane.showConfirmDialog(null, accp,"Choose RGB Color", JOptionPane.OK_CANCEL_OPTION);
                        if(reply== JOptionPane.OK_OPTION){
                            
                            red = cc.getColor().getRed(); txt_red2.setText(red+"");
                            green = cc.getColor().getGreen(); txt_green2.setText(green+"");
                            blue = cc.getColor().getBlue(); txt_blue2.setText(blue+"");

                            
                            float hsl[]=rgbToHsl(red,green,blue);
                            txt_h1.setText(hsl[0]+"");
                            txt_s1.setText(hsl[1]+"");
                            txt_l.setText(hsl[2]+"");
                            
                            jTextField1.setBackground(cc.getColor());
                        }
                    }
                }
    }//GEN-LAST:event_btn_rgbTOhslActionPerformed

    private void btn_hslTOrgbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hslTOrgbActionPerformed
        // TODO add your handling code here:
        JColorChooser cc = new JColorChooser();
                AbstractColorChooserPanel[] panels = cc.getChooserPanels();
                for (AbstractColorChooserPanel accp : panels) {
                    if (accp.getDisplayName().equals("HSL")) {
                        int reply=JOptionPane.showConfirmDialog(null, accp,"Choose HSL Color", JOptionPane.OK_CANCEL_OPTION);
                        if(reply== JOptionPane.OK_OPTION){
                            
                            red = cc.getColor().getRed(); txt_red2.setText(red+"");
                            green = cc.getColor().getGreen(); txt_green2.setText(green+"");
                            blue = cc.getColor().getBlue(); txt_blue2.setText(blue+"");
                            float hsl[]=new float[4];
                            cc.getColor().getColorSpace().toCIEXYZ(hsl);
                            
                            txt_h1.setText(hsl[0]+"");
                            txt_s1.setText(hsl[1]+"");
                            txt_l.setText(hsl[2]+"");
                            
                            jTextField1.setBackground(cc.getColor());
                        }
                    }
                }
    }//GEN-LAST:event_btn_hslTOrgbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_hsbTOrgb;
    private javax.swing.JToggleButton btn_hslTOrgb;
    private javax.swing.JToggleButton btn_rgbTOhsb;
    private javax.swing.JToggleButton btn_rgbTOhsl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton toggle_fromCMYK;
    private javax.swing.JToggleButton toggle_rgbToCMYK;
    private javax.swing.JTextField txt_b;
    private javax.swing.JTextField txt_black;
    private javax.swing.JTextField txt_blue;
    private javax.swing.JTextField txt_blue1;
    private javax.swing.JTextField txt_blue2;
    private javax.swing.JTextField txt_cyan;
    private javax.swing.JTextField txt_green;
    private javax.swing.JTextField txt_green1;
    private javax.swing.JTextField txt_green2;
    private javax.swing.JTextField txt_h;
    private javax.swing.JTextField txt_h1;
    private javax.swing.JTextField txt_l;
    private javax.swing.JTextField txt_magenta;
    private javax.swing.JTextField txt_red;
    private javax.swing.JTextField txt_red1;
    private javax.swing.JTextField txt_red2;
    private javax.swing.JTextField txt_s;
    private javax.swing.JTextField txt_s1;
    private javax.swing.JTextField txt_yellow;
    // End of variables declaration//GEN-END:variables

    private float [] rgbToHsl(int r1,int g1, int b1) {
        float r = (float)(r1/255);
        float g =(float) (g1/255);
        float b = (float) b1/255;
        int max = (int) Math.max(b,Math.max(r, g));
        int min = (int) Math.min(b,Math.min(r, g));
        float h= 0;
        float s=0;
        float l= ((max + min) / 2)*100;
        
        if (max == min) {
            s = 0; // achromatic
        } 
        else {
            if(l>50){
                s= 100*((max-min)/(2-max-min));
            }
            else{
                s=100*((max-min)/(max+min));
            }
        }
        
        if(max==r){
            h=(int) (100*((g-b)/(max-min)));
        }
        else if(max==g){
            h=(int) (100*((2.0 + (b-r)/(max-min))));
        }
        else if(max== b){
            h=(int) (100*(4.0 + (r-g)/(max-min)));
        }
        float hsl[]={h,s,l};
        return hsl;
    }

    private float [] hslTorgb() {
        float hsl[]=null;
        
        return hsl;
    }
}
